name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Unity/Library
          key: Library-Unity-${{ hashFiles('Unity/Assets/**', 'Unity/Packages/**', 'Unity/ProjectSettings/**') }}
          restore-keys: |
            Library-Unity-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Unity
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          docker system prune -af
          sudo apt-get clean
          sudo rm -rf /opt/hostedtoolcache

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Unity
          targetPlatform: WebGL

      # Replace index.html
      - name: Replace index.html with custom one
        run: cp JS/index.html build/WebGL/index.html

      # Create text-alive.js
      - name: Create text-alive.js
        run: cp JS/text-alive.js build/WebGL/text-alive.js

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
